"""audit.json + before.json + detect.json -> metrics.md (and metrics.json for the gallery)."""
import json, collections, os
R = os.path.join(os.path.dirname(__file__), '..')
a = json.load(open(f'{R}/audit.json')); bf = json.load(open(f'{R}/before.json')); scr = json.load(open(f'{R}/screens.json'))
det = json.load(open(f'{R}/detect.json'))
dc = collections.Counter(f['antipattern'] for f in det)
fails = lambda v: len(v['small']) + len(v['contrast']) + len(v['fillText']) + len(v['tiny']) + (1 if v['overflowX'] > 0 else 0) + v['nested']
L = []
L.append('# Mockup metrics\n\nGenerated by `tools/report.py` from `audit.json` (Playwright, `tools/audit.mjs`), `before.json` (same collector on the current app, `?demo`) and `detect.json` (Impeccable `detect`).\n')
tot = len(a); bad = [k for k, v in a.items() if fails(v)]
L.append(f'## Checks\n\n{len(scr)} screens × paper + dark × 390×844 + 320×640 = **{tot} runs**. Runs with any failure: **{len(bad)}**.\n')
L.append('| Check | Rule | Failing runs |\n|---|---|---|')
for name, key, rule in [('Horizontal scroll', 'overflowX', 'page wider than the viewport'), ('Text under 11px', 'small', 'any visible text node'), ('Tap targets', 'tiny', 'every control ≥ 44×44 (bars included)'),
                        ('Contrast', 'contrast', 'text ≥ 4.5:1 (≥ 3:1 at 24px+) on its painted background'), ('Text in a fill colour', 'fillText', 'paper: no text in gold, macro hues, bar purple'), ('Card in a card', 'nested', 'framed or filled block inside another')]:
    n = sum(1 for v in a.values() if (v[key] > 0 if key in ('overflowX', 'nested') else v[key]))
    L.append(f'| {name} | {rule} | {n} |')
L.append(f'\nImpeccable `detect` over all {len(scr) * 2} files + `system.css`: ' + ', '.join(f'**{k}** ×{n}' for k, n in dc.items()) +
         '. That one rule flags the paper/cream page on every file; the brief keeps the paper, so it stands (the brief wins over Impeccable taste rules). No other findings: no side stripes, no offset shadows, no type under 11px, no eyebrow labels, no clip-path shapes, no glow.\n')
# before / after
L.append('## Before → after (390×844, paper, the screens that exist in both)\n')
L.append('Primary y = top of the screen\'s primary content in CSS px (inside the sheet for sheets). Blocks = framed or filled surfaces ≥ 120×36 (controls, sprites, scenes and charts excluded). Controls = tappable things outside the app bar and tab bar. Help = sentences of 5+ words ending . ! ? outside controls and the buddy\'s line. Under-44 and under-11px count every instance.\n')
L.append('| Screen | Primary y | Blocks (nested) | Controls | Help | Buddy lines | <44px targets | <11px text |\n|---|---|---|---|---|---|---|---|')
pairs = [('today', 'today'), ('food', 'food'), ('cook', 'cook'), ('train', 'train'), ('progress', 'progress'), ('you', 'you'), ('play', 'play'), ('log', 'log')]
for b, m in pairs:
    x, y = bf[f'{b}|paper|390'], a[f'{m}|paper|390']
    f = lambda k: (x[k], y[k])
    L.append(f'| {b.title() if b != "log" else "Log sheet"} | {x["primaryY"]} → **{y["primaryY"]}** | {x["blocks"]} ({x["nested"]}) → **{y["blocks"]} ({y["nested"]})** | {x["controls"]} → **{y["controls"]}** | {len(x["help"])} → **{len(y["help"])}** | – → {y["buddy"]} | {len(x["tiny"])} → **{len(y["tiny"])}** | {len(x["small"])} → **{len(y["small"])}** |')
L.append('\nNotes: the "before" app is `main` at `bcf019b`, after Reset 01–02 (Today was already partly calmed). Its Play is a modal and was measured inside it. Before-app primary locators: Today "kcal left", Food first entry, Cook first recipe, Train "Lower B", Progress verdict, You first row, Play the buddy\'s name, Log the search field.\n')
# all screens
L.append('## Every screen (390×844, paper; dark and 320×640 have the same counts and pass the same checks)\n')
L.append('| Group | Screen | Primary y | Blocks | Controls | Help | Buddy | Fails (all 4 runs) |\n|---|---|---|---|---|---|---|---|')
for s in scr:
    v = a[f'{s["id"]}|paper|390']
    fa = sum(fails(a[f'{s["id"]}|{t}|{w}']) for t in ('paper', 'dark') for w in (390, 320))
    L.append(f'| {s["group"]} | {s["title"]} | {v["primaryY"]} | {v["blocks"]} | {v["controls"]} | {len(v["help"])} | {v["buddy"]} | {fa} |')
open(f'{R}/metrics.md', 'w').write('\n'.join(L) + '\n')
json.dump({'pairs': [[b, m, bf[f'{b}|paper|390'], a[f'{m}|paper|390']] for b, m in pairs], 'runs': tot, 'bad': len(bad), 'detect': dc}, open(f'{R}/metrics.json', 'w'))
print('\n'.join(L[:40]))
