#!/usr/bin/env python3
"""The Handheld icon set (design-plans/35-reset/03-direction-c.md).

One family on a 24x24 grid of 2px cells, outline style with a one-cell stroke: the house look of
pixelarticons (https://github.com/halfmage/pixelarticons, MIT, (c) 2019 Gerrit Halfmann), which this
set uses for the UI marks it covers well. Everything it has no answer for - the food kinds, the egg,
the training and game marks - is drawn here in the same cell size and stroke, so the two read as one.

    python3 tools/c-icons.py <pixelarticons-raster.json>   # writes design-exports/macrosaurus-icons-24.json
    node tools/gen-px-icons.mjs                             # copies it into app/src/app.jsx

The raster JSON maps a pixelarticons name to its 24 rows of '#'/'.', rendered 1:1 from the SVG.
Names are the app's existing icon names, so no call site changes.
"""
import json, os, sys

# app name -> pixelarticons name, for the marks it draws well
PXA = {
    'arrow_left': 'arrow-left', 'arrow_up': 'arrow-up', 'barcode': 'barcode',
    'calendar': 'calendar', 'cam': 'camera', 'cart': 'shopping-cart', 'chat': 'message', 'check': 'check',
    'chevron': 'chevron-right', 'close': 'close', 'corner_arrow': 'corner-down-left',
    'edit': 'pencil', 'figure': 'human', 'info': 'circle-info',
    'lock': 'lock', 'mic': 'mic', 'moon': 'moon', 'photo': 'image',
    'plant': 'leaf', 'play': 'play', 'plus': 'plus', 'share': 'upload', 'sliders': 'sliders-vertical',
    'square': 'square', 'sun': 'sun',
    'trend_up': 'trending-up', 'trophy': 'trophy',
}

# Drawn here on the 12-cell grid (one character = one 2px cell), in the same outline weight.
C = {}
C['dash'] = """
............
............
.#...##...#.
..#......#..
....####....
...#....#...
..#......#..
.##########.
............
..########..
............
............"""  # Today: the sun coming up over the horizon
C['dot'] = """
............
............
............
............
....####....
...######...
...######...
....####....
............
............
............
............"""
C['caret_down'] = """
............
............
............
............
..########..
...######...
....####....
.....##.....
............
............
............
............"""
C['tri_down'] = """
............
............
............
............
..########..
...######...
....####....
.....##.....
............
............
............
............"""
C['dumbbell'] = """
............
............
............
.##......##.
.##......##.
.##########.
.##########.
.##......##.
.##......##.
............
............
............"""
C['food'] = """
............
..#.#.#..##.
..#.#.#..#..
..#.#.#..#..
..#####..#..
...###...#..
....#....##.
....#....#..
....#....#..
....#....#..
............
............"""
C['recipe'] = """
............
.....##.....
....####....
............
.##########.
..#......#..
..#......#..
..#......#..
..#......#..
...######...
............
............"""
C['egg'] = """
............
....####....
...#....#...
..#.##...#..
..#.##...#..
.#........#.
.#.....##.#.
.#.....##.#.
.#........#.
..#......#..
...######...
............"""
C['meat'] = """
............
.....####...
....#....#..
...#......#.
...#......#.
...#.....#..
...#....#...
..##.###....
.#..#.......
.#.#........
..#.........
............"""
C['drink'] = """
............
.##########.
..#......#..
..##....##..
...#....#...
....#..#....
.....##.....
.....##.....
.....##.....
...######...
............
............"""
C['grain'] = """
............
.....##.....
....####....
..##.##.##..
...######...
..##.##.##..
...######...
.....##.....
.....##.....
.....##.....
.....##.....
............"""
C['drop'] = """
............
.....##.....
....#..#....
....#..#....
...#....#...
..#......#..
..#......#..
..#.#....#..
..#..#...#..
...#....#...
....####....
............"""
C['glove'] = """
............
...######...
..#......#..
.#........#.
.#........#.
.#.###....#.
.#....#...#.
..#...#..#..
...######...
...#....#...
...######...
............"""
C['flashlight'] = """
............
.......#..#.
........##..
......####..
.....#..#...
....#..#....
...#..#.....
..#..#......
.#..#.......
.###........
............
............"""
C['scale'] = """
............
.##########.
.#........#.
.#..####..#.
.#...##...#.
.#........#.
.#........#.
.#........#.
.#........#.
.##########.
............
............"""


# Drawn here rather than taken from pixelarticons: these run full-bleed there (22px), which breaks the
# 20px live area every other glyph keeps.
C['gear'] = """
............
.....##.....
..##.##.##..
..#......#..
...#.##.#...
.##.#..#.##.
.##.#..#.##.
...#.##.#...
..#......#..
..##.##.##..
.....##.....
............"""
C['heart_empty'] = """
............
............
..##....##..
.#..#..#..#.
.#...##...#.
.#........#.
..#......#..
...#....#...
....#..#....
.....##.....
............
............"""
C['star'] = """
............
.....##.....
....#..#....
....#..#....
.###....###.
.#........#.
..#......#..
...#....#...
..#..##..#..
..#.#..#.#..
..##....##..
............"""
C['more'] = """
............
............
............
............
............
.##..##..##.
.##..##..##.
............
............
............
............
............"""
C['snow'] = """
............
.....##.....
..#..##..#..
...#.##.#...
....####....
.##########.
.##########.
....####....
...#.##.#...
..#..##..#..
.....##.....
............"""
C['bolt'] = """
............
............
......###...
.....###....
....###.....
...#######..
.....###....
....###.....
...###......
...##.......
............
............"""
C['goal'] = """
............
...######...
..#......#..
.#..####..#.
.#.#....#.#.
.#.#.##.#.#.
.#.#.##.#.#.
.#.#....#.#.
.#..####..#.
..#......#..
...######...
............"""
C['sweet'] = """
............
.....##.....
...######...
..#......#..
.#........#.
.##########.
..#.#..#.#..
..#.#..#.#..
...#....#...
...######...
............
............"""
C['dino'] = """
............
......#####.
......#.###.
......#####.
......###...
.#...#####..
.##.######..
..#######...
...#####....
....#..#....
....##.##...
............"""

def rows(a): return a.strip('\n').split('\n')
def double(g): return [''.join(c * 2 for c in r) for r in g for _ in (0, 1)]
flipH = lambda g: [r[::-1] for r in g]
flipV = lambda g: list(reversed(g))

def fill_inside(g):
    """Flood the outside from the edges; whatever is neither ink nor outside is the inside."""
    H, W = len(g), len(g[0]); out = [[False] * W for _ in range(H)]
    st = [(x, y) for x in range(W) for y in (0, H - 1)] + [(x, y) for y in range(H) for x in (0, W - 1)]
    while st:
        x, y = st.pop()
        if 0 <= x < W and 0 <= y < H and not out[y][x] and g[y][x] == '.':
            out[y][x] = True; st += [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]
    return [''.join('#' if g[y][x] == '#' or not out[y][x] else '.' for x in range(W)) for y in range(H)]

def shift(g, dx, dy):
    H, W = len(g), len(g[0])
    return [''.join(g[y - dy][x - dx] if 0 <= y - dy < H and 0 <= x - dx < W else '.' for x in range(W)) for y in range(H)]

def fit(g):
    """Centre a glyph on the 24 box without redrawing it."""
    ys = [y for y, r in enumerate(g) if '#' in r]; xs = [x for r in g for x, c in enumerate(r) if c == '#']
    dx = round(((23 - max(xs)) - min(xs)) / 2); dy = round(((23 - max(ys)) - min(ys)) / 2)
    return shift(g, dx, dy)

def check(name, g):
    errs = []
    if len(g) != 24 or any(len(r) != 24 for r in g): return ['not 24x24']
    for i in range(24):
        for x, y in [(i, 0), (i, 1), (i, 22), (i, 23), (0, i), (1, i), (22, i), (23, i)]:
            if g[y][x] == '#': errs.append(f'margin {x},{y}')
    lit = lambda x, y: 0 <= x < 24 and 0 <= y < 24 and g[y][x] == '#'
    for y in range(24):
        for x in range(24):
            if lit(x, y) and not (lit(x - 1, y) or lit(x + 1, y) or lit(x, y - 1) or lit(x, y + 1)):
                errs.append(f'1x1 at {x},{y}')
    xs = [x for r in g for x, c in enumerate(r) if c == '#']; ys = [y for y, r in enumerate(g) if '#' in r]
    if abs((min(xs) + max(xs)) / 2 - 11.5) > 1: errs.append('off-centre x')
    if abs((min(ys) + max(ys)) / 2 - 11.5) > 1: errs.append('off-centre y')
    return sorted(set(errs))[:3]

def halves(g): return all(g[y][x] == g[y - (y % 2)][x - (x % 2)] for y in range(24) for x in range(24))

if __name__ == '__main__':
    raster = json.load(open(sys.argv[1]))
    G = {}
    for app, pxa in PXA.items(): G[app] = fit(raster[pxa])
    for k, v in C.items(): G[k] = double(rows(v))
    G['heart_full'] = fill_inside(G['heart_empty'])
    G['arrow_right'] = flipH(G['arrow_left'])
    G['caret_up'] = flipV(G['caret_down'])
    G['tri_up'] = flipV(G['tri_down'])
    G['trend_down'] = flipV(G['trend_up'])
    # check and star render inline at 12px, so they must halve cleanly: snap them to the even sub-grid
    for k in ('check', 'star'):
        if not halves(G[k]):
            for dx, dy in ((1, 0), (0, 1), (1, 1), (-1, 0), (0, -1), (-1, -1)):
                h = shift(G[k], dx, dy)
                if halves(h): G[k] = h; break
    bad = {k: e for k, g in G.items() for e in [check(k, g)] if e}
    for k, e in bad.items(): print('FIX', k, e)
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
    path = os.path.join(root, 'design-exports', 'macrosaurus-icons-24.json')
    art = json.load(open(path))
    missing = set(art['icons']) - set(G)
    if missing: print('missing', sorted(missing)); sys.exit(1)
    if bad and '--force' not in sys.argv: sys.exit(1)
    art['meta'] = dict(art.get('meta', {}), set='Handheld (35-reset direction C)',
                       credit='UI marks from pixelarticons (MIT, Gerrit Halfmann); food, training and game marks drawn for Macrosaurus',
                       source='tools/c-icons.py')
    art['icons'] = {k: G[k] for k in sorted(art['icons'])}
    json.dump(art, open(path, 'w'), indent=1)
    print('wrote', len(art['icons']), 'icons')
